# Generated by Django 5.1.5 on 2025-01-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myOrders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
