# Generated by Django 5.1.5 on 2025-01-28 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myOrders', '0002_remove_order_time_alter_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
