name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Adjust if your branch name is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Heroku CLI
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "customerorders"  # Replace with your actual Heroku app name
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Run database migrations
        run: |
          heroku run python manage.py migrate --app customerorders

      - name: Collect static files
        run: |
          heroku run python manage.py collectstatic --noinput --app customerorders
