name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Find and Set Project Path
        run: |
          if [ -f "orders/manage.py" ]; then
            echo "PROJECT_PATH=orders" >> $GITHUB_ENV
          else
            echo "Error: manage.py not found!"
            exit 1
          fi

      - name: Create Virtual Environment & Install Dependencies
        run: |
          cd $PROJECT_PATH
          python -m venv venv  # Create virtual environment
          source venv/bin/activate
          pip install --upgrade pip
          pip install --no-cache-dir psycopg2-binary  # Ensure psycopg2-binary is installed
          pip install -r requirements.txt

      - name: Verify Installed Packages
        run: |
          cd $PROJECT_PATH
          source venv/bin/activate
          pip freeze  # Check installed dependencies

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          export PATH="/usr/local/bin:$PATH"
          heroku --version  # Verify Heroku installation

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | heroku auth:token

      - name: Ensure Database Exists (Optional)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku addons:info heroku-postgresql --app customerorders || \
          heroku addons:create heroku-postgresql:hobby-dev --app customerorders

      - name: Run Migrations and Collect Static Files
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku run python manage.py migrate --noinput --app customerorders || echo "Skipping migrations"
          heroku run python manage.py collectstatic --noinput --clear --app customerorders || echo "Skipping collectstatic"

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote -a customerorders
          git push heroku main
